name: Backup

on: push

jobs:
  backup:
    env:
      GH_SOURCE_ACCOUNT: ${{ secrets.GH_SOURCE_ACCOUNT }}
      GH_BACKUP_ACCOUNT: ${{ secrets.GH_BACKUP_ACCOUNT }}
      GH_BACKUP_ACCOUNT_TOKEN: ${{ secrets.GH_BACKUP_ACCOUNT_TOKEN }}
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Setup SSH Keys and known_hosts
        run: |
          mkdir -p ~/.ssh
          eval `ssh-agent -s`
          echo "IdentityFile ~/.ssh/server_key" >> ~/.ssh/config
          echo "${{ secrets.SSH_PRIVATE_KEY }}" >> ~/.ssh/server_key
          chmod 400 ~/.ssh/server_key
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Run scripts
        run: npm start
